{{- if .Values.s3InitJob.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-init-job-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "all_objects_labels_shs" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.initJobCredentialsSecret.annotations | nindent 4}}
data:
 s3_accessKey: {{ .Values.s3.accesskey | b64enc }}
 s3_secretKey: {{ .Values.s3.secretkey | b64enc }}
{{- end }}