{{- if .Values.kerberos.enabled }}
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-keytab
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    {{- include "all_objects_labels_shs" . | nindent 4 }}
kind: Secret
type: Opaque
data:
  {{- if .Values.kerberos.keytab }}
  hdfs.keytab: |
    {{- .Values.kerberos.keytab | nindent 4 }}
  {{- end }}
{{- end }}
