{{- if .Values.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-s3-creds
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    {{- include "all_objects_labels_shs" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.s3.accesskey }}
  secret-key: {{ .Values.s3.secretkey }}
  jceks.pass: {{ .Values.s3.jceksPassword }}
{{- end }}