{{- if .Values.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-s3-creds
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    {{- include "all_objects_labels_shs" . | nindent 4 }}
type: Opaque
data:
  accesskey: {{ .Values.s3.accesskey | b64enc }}
  secretkey: {{ .Values.s3.secretkey | b64enc }}
{{- end }}