apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-pi-servicemonitor
  labels:
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      sparkoperator.k8s.io/app-name: spark-pi-long-run-metrics
  endpoints:
    - port: spark-driver-ui-port
      path: /metrics/executors/prometheus
      interval: 30s
    - port: spark-driver-ui-port
      path: /metrics/prometheus
      interval: 30s