apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark-thrift-server.fullname" . }}-service
  labels:
    {{- include "all_objects_labels_sts" . | nindent 4 }}
    {{- include "deployment_and_service_only_labels_sts" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.ports.thriftServerPort.name }}
      protocol: {{ .Values.service.ports.thriftServerPort.protocol }}
      port: {{ .Values.service.ports.thriftServerPort.port }}
      targetPort: {{ .Values.service.ports.thriftServerPort.targetPort }}
      nodePort: {{ .Values.service.ports.thriftServerPort.nodePort }}
    - name: {{ .Values.service.ports.sparkDriverPort.name }}
      protocol: {{ .Values.service.ports.sparkDriverPort.protocol }}
      port: {{ .Values.service.ports.sparkDriverPort.port }}
      targetPort: {{ .Values.service.ports.sparkDriverPort.targetPort }}
    - name: {{ .Values.service.ports.sparkUIPort.name }}
      protocol: {{ .Values.service.ports.sparkUIPort.protocol }}
      port: {{ .Values.service.ports.sparkUIPort.port }}
      targetPort: {{ .Values.service.ports.sparkUIPort.targetPort }}
      nodePort: {{ .Values.service.ports.sparkUIPort.nodePort }}
    {{- range .Values.service.ports.additionalPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      nodePort: {{ .nodePort }}
    {{- end }}
  selector:
    {{- include "selector_labels_sts" . | nindent 4 }}
