apiVersion: v1
kind: Secret
metadata:
  name: s3-cred
  namespace: spark-apps
type: Opaque
stringData:
  core-site.xml: |
    <configuration>
      <property>
        <name>fs.s3a.access.key</name>
        <value>Z4nz2bxWnWM36lf3K21y</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>oqtAdywaB7c7OJWHQ9rLVuJcKjpUR8iSJfXMPCLr</value>
      </property>
    </configuration>   