{{- if and .Values.oauth2Proxy.config.google (and (not .Values.oauth2Proxy.config.google.existingSecret) (not .Values.oauth2Proxy.config.google.useApplicationDefaultCredentials)) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "oauth2-proxy.name" . }}
  {{- include "oauth2-proxy.labels" . | indent 4 }}
name: {{ template "oauth2-proxy.fullname" . }}-google
namespace: {{ template "oauth2-proxy.namespace" $ }}
type: Opaque
data:
  service-account.json: {{ .Values.oauth2Proxy.config.google.serviceAccountJson | b64enc | quote }}
  {{- end -}}
