{{- if and (not .Values.oauth2Proxy.config.existingSecret) (.Values.oauth2Proxy.proxyVarsAsSecrets) }}
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.oauth2Proxy.config.annotations }}
  annotations:
{{ toYaml .Values.oauth2Proxy.config.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}
type: Opaque
data:
  cookie-secret: {{ tpl .Values.oauth2Proxy.config.cookieSecret $ | b64enc | quote }}
  client-secret: {{ tpl .Values.oauth2Proxy.config.clientSecret $ | b64enc | quote }}
  client-id: {{ tpl .Values.oauth2Proxy.config.clientID $ | b64enc | quote }}
{{- end -}}
