apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark-history-server.fullname" . }}
  labels:
    {{- include "all_objects_labels_shs" . | nindent 4 }}
    {{- include "deployment_and_service_only_labels_shs" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Chart.Name }}
  selector:
    {{- include "selector_labels_shs" . | nindent 4 }}
