{{- if .Values.hiveConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: hive-cfg-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "all_objects_labels_sts" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.hiveConfigSecret.hiveSiteProperties }}
  hive-site.xml:  |-
    {{ tpl .Values.hiveConfigSecret.hiveSiteProperties . | b64enc }}
  {{- end }}
  {{- if .Values.hiveConfigSecret.coreSiteProperties }}
  core-site.xml:  |-
    {{ tpl .Values.hiveConfigSecret.coreSiteProperties . | b64enc }}
  {{- end }}
  {{- if .Values.hiveConfigSecret.hdfsSiteProperties }}
  hdfs-site.xml: |-
    {{ tpl .Values.hiveConfigSecret.hdfsSiteProperties . | b64enc }}
  {{- end }}
{{- end }}