apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j2-properties
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "all_objects_labels_sts" . | nindent 4 }}
data:
  log4j2.properties: | #log4j properties
     {{- if .Values.log4j2Properties }}
       {{- .Values.log4j2Properties | nindent 4 }}
     {{- end }}