apiVersion: v1
kind: ConfigMap
metadata:
 name: pod-template
 namespace: {{ .Release.Namespace }}
 labels:
  {{- include "all_objects_labels_sts" . | nindent 2 }}
data:
 pod-template.yaml: |
   kind: Pod
   spec:
     containers:
       - name: spark-thrift-executor
         securityContext:
           {{- if eq (default "KUBERNETES" .Values.PAAS_PLATFORM) "OPENSHIFT" }}
           {{- toYaml (omit .Values.securityContext "runAsUser") | nindent 10 }}
           {{- else }}
           {{- toYaml .Values.securityContext | nindent 10 }}
           {{- end }}
           