apiVersion: v1
kind: Secret
metadata:
  name: spark-thrift-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "all_objects_labels_sts" . | nindent 4 }}
type: Opaque
data:
  accesskey: {{ .Values.s3.accesskey | b64enc }}
  secretkey: {{ .Values.s3.secretkey | b64enc }}