{{- if .Values.oauth2Proxy.enabled }}
{{- if not .Values.oauth2Proxy.config.existingConfig }}
{{- if .Values.oauth2Proxy.config.configFile }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- with .Values.oauth2Proxy.config.annotations }}
  annotations:
{{ tpl ( toYaml . ) $ | indent 4 }}
{{- end }}
  labels:
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}
  namespace: {{ template "oauth2-proxy.namespace" $ }}
data:
  oauth2_proxy.cfg: {{ tpl .Values.oauth2Proxy.config.configFile $ | quote }}
{{- end }}
{{- end }}
{{- end }}
