{{- if .Values.oauth2Proxy.enabled }}
{{-
  if and
    .Values.oauth2Proxy.alphaConfig.enabled
    (not .Values.oauth2Proxy.alphaConfig.existingConfig)
    (not .Values.oauth2Proxy.alphaConfig.existingSecret)
}}
apiVersion: v1
kind: Secret
metadata:
{{- with .Values.oauth2Proxy.alphaConfig.annotations }}
  annotations:
{{ tpl ( toYaml . ) $ | indent 4 }}
{{- end }}
  labels:
    app: {{ template "oauth2-proxy.name" . }}
    {{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}-alpha
  namespace: {{ template "oauth2-proxy.namespace" $ }}
data:
  oauth2_proxy.yml: {{ include "oauth2-proxy.alpha-config" . | b64enc | quote }}
{{- end }}
{{- end }}