{{- if .Values.oauth2Proxy.enabled }}
{{- if .Values.oauth2Proxy.authenticatedEmailsFile.enabled }}
{{- if and (.Values.oauth2Proxy.authenticatedEmailsFile.restricted_access) (eq .Values.oauth2Proxy.authenticatedEmailsFile.persistence "secret")  }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
{{- with .Values.oauth2Proxy.authenticatedEmailsFile.annotations }}
  annotations:
{{ tpl ( toYaml . ) $ | indent 4 }}
{{- end }}
  name: {{ template "oauth2-proxy.fullname" . }}-accesslist
  namespace: {{ template "oauth2-proxy.namespace" $ }}
data:
  {{ default "restricted_user_access" .Values.oauth2Proxy.authenticatedEmailsFile.restrictedUserAccessKey }}: {{ .Values.oauth2Proxy.authenticatedEmailsFile.restricted_access | b64enc }}
{{- end }}
{{- end }}
{{- end }}
