kind: Secret
apiVersion: v1
metadata:
  name: ca-certificates
  namespace: spark-apps
type: Opaque  
stringData:
  hive.pem: |
    -----BEGIN CERTIFICATE-----
    hive metastore certificate content
    -----END CERTIFICATE-----
  s3.pem: |
    -----BEGIN CERTIFICATE-----
    s3 certificate content
    -----END CERTIFICATE----- 