apiVersion: v1
kind: Secret
metadata:
  name: hive-cert
  namespace: spark-apps
type: Opaque
stringData:
  hive.pem: |
    -----BEGIN CERTIFICATE-----
    certificate content
    -----END CERTIFICATE-----
    