apiVersion: v1
kind: Secret
metadata:
  name: s3-cert
  namespace: spark-apps
type: Opaque
stringData:
  s3.pem: |
    -----BEGIN CERTIFICATE-----
    certificate content
    -----END CERTIFICATE-----
    