apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-secrets
  namespace: spark-apps
type: Opaque
stringData:
  WAREHOUSE_URI: seaweedfs://{filer host}:8888/hive/warehouse
  DB_NAME: {database name}
  TABLE_NAME: {table name}
