apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-hive-test
  namespace: spark-apps
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "artifactorycn.netcracker.com:17009/netcracker/qubership-spark-hive-test:improvement-support_to_hive4-v2"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/spark_hive_test.py"
  sparkVersion: "3.1.3"
  sparkConf:
    "spark.jars.ivy": "/tmp/.ivy"
  #"spark.kubernetes.local.dirs.tmpfs": "true"
    "spark.kubernetes.submission.connectionTimeout": "60000000"
    "spark.kubernetes.submission.requestTimeout": "60000000"
    "spark.kubernetes.driver.connectionTimeout": "60000000"
    "spark.kubernetes.driver.requestTimeout": "60000000"		
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "2g"
    labels:
      version: 3.1.3
    serviceAccount: sparkapps-sa
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 185
      capabilities:
        drop:
        - ALL  
  executor:
    cores: 1
    instances: 1
    memory: "2g"
    labels:
      version: 3.1.3
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 185
      capabilities:
        drop:
          - ALL
