{{- define "sparkOperatorCertDnsNames" -}}
  {{- $dnsNames := list "localhost" "spark-operator" (printf "%s.%s" "spark-operator" .Release.Namespace) (printf "%s.%s.svc" "spark-operator" .Release.Namespace) -}}
    {{- $dnsNames = concat $dnsNames .Values.spark-operator.certManagerIntegration.subjectAlternativeName.additionalDnsNames -}}
  {{- $dnsNames | toYaml -}}
{{- end -}}

{{- define "sparkOperatorCertIpAddresses" -}}
  {{- $ipAddresses := list "127.0.0.1" -}}
  {{- $ipAddresses = concat $ipAddresses .Values.spark-operator.certManagerIntegration.subjectAlternativeName.additionalIpAddresses -}}
  {{- $ipAddresses | toYaml -}}
{{- end -}}

{{- if .Values.spark-operator.certManagerIntegration.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spark-operator-tls-certificate
  labels:
    {{- include "all_objects_labels_shs" . | nindent 4 }}
    {{- include "cert_manager_label_shs" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "-11"
spec:
  secretName: {{ .Values.spark-operator.certManagerIntegration.secretName }}
  duration: {{ default 365 .Values.spark-operator.certManagerIntegration.duration | mul 24 }}h
  commonName: spark-operator.svc
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
{{ ( include "sparkOperatorCertDnsNames" . | indent 4 ) }}
  ipAddresses:
{{ ( include "sparkOperatorCertIpAddresses" . | indent 4 ) }}
  issuerRef:
    group: cert-manager.io
  {{- if .Values.spark-operator.certManagerIntegration.clusterIssuerName }}
    name: {{ .Values.spark-operator.certManagerIntegration.clusterIssuerName }}
    kind: ClusterIssuer
  {{- else }}
    name: spark-operator-tls-issuer
    kind: Issuer
  {{- end }}
{{- end }}
