{{- if .Values.certManagerIntegration.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: spark-operator-tls-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "all_objects_labels_shs" . | nindent 4 }}
    {{- include "cert_manager_label_shs" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
