{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ .Values.serviceAccount.name }}-service-operator
  namespace: {{ .Values.sparkAppsNamespace }}
  labels:
    {{- include "all_objects_labels_ssit" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - sparkapplications
      - sparkapplications/status
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - update
{{- end }}
