apiVersion: v1
kind: Secret
metadata:
  name: s3-connection-config
  namespace: {{ .Values.sparkAppsNamespace }}
  labels:
    {{- include "all_objects_labels_ssit" . | nindent 4 }}
type: Opaque
stringData:
  core-site.xml: |
    <configuration>
      <property>
        <name>fs.s3a.access.key</name>
        <value>{{ .Values.s3.accessKey }}</value>
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>{{ .Values.s3.secretKey }}</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>{{ .Values.s3.endpointUrl }}</value>
      </property>
    </configuration>   