apiVersion: v1
kind: Secret
metadata:
  name: s3-secrets
  namespace: {{ .Values.sparkAppsNamespace }}
  labels:
    {{- include "all_objects_labels_ssit" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{.Values.s3.secretKey }}
  S3_ENDPOINT_URL: {{ .Values.s3.endpointUrl }}
  BUCKET_NAME: {{ .Values.s3.bucketName }}
  DB_NAME: {{ .Values.s3.dbName }}
  TABLE_NAME: {{ .Values.s3.tableName }}

