name: Build Test Images
on:
  workflow_dispatch:
    inputs:
      publish_docker:
        description: "Publish image to ghcr.io"
        type: boolean
        default: true
        required: false

env:
  TAG_NAME: ${{ github.event.release.tag_name || github.ref }}
  PUSH: ${{ (github.event_name == 'workflow_dispatch' && inputs.publish_docker) || !startsWith(github.ref, 'refs/heads/dependabot') }}
  GITHUB_GROUP: ${{ github.repository_owner }}

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-tests-spark-pi-long-run
            file: spark-sample-apps/spark-pi-long-run/Dockerfile
            context: spark-sample-apps/spark-pi-long-run
          - name: qubership-tests-spark-streaming-checkpoint
            file: spark-sample-apps/spark-streaming-checkpoint/Dockerfile
            context: spark-sample-apps/spark-streaming-checkpoint/
          - name: qubership-tests-spark-streaming-word-count
            file: spark-sample-apps/spark-streaming-word-count/Dockerfile
            context: spark-sample-apps/spark-streaming-word-count
          - name: qubership-tests-spark-word-count-s3
            file: spark-sample-apps/word-count-s3/Dockerfile
            context: spark-sample-apps/word-count-s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Prepare Group
        run: echo "GITHUB_GROUP=${GITHUB_GROUP,,}" >> $GITHUB_ENV
      - name: Get package IDs for delete
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ env.PUSH }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64 # ToDo add linux/arm64
          push: true
          tags: ghcr.io/${{ env.GITHUB_GROUP }}/${{ matrix.component.name }}:${{ env.TAG_NAME }}
          provenance: false
          build-args: |
            GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
            base_img=ghcr.io/netcracker/qubership-spark-customized:${{ env.TAG_NAME }}
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.component.name }}
          package-type: 'container'
          package-version-ids: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
        if: ${{ steps.get-ids-for-delete.outputs.ids-for-delete != '' }}