{
 "title": "Spark Application Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "spark_app_id",
    "label": "Spark Application Id",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}, application_id)"
    }
   },
   {
    "name": "spark_app_id_postfix",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{cluster=\"$cluster\", namespace=\"$namespace\", application_id=\"$spark_app_id\"}, application_id)"
    }
   },
   {
    "name": "spark_app_id_prefix",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{cluster=\"$cluster\",namespace=\"$namespace\",application_id=\"$spark_app_id\"}, application_id)"
    }
   },
   {
    "name": "application_name",
    "query": {
     "query": "label_values(metrics_executor_memoryUsed_bytes{cluster=\"$cluster\",namespace=\"$namespace\",application_id=\"$spark_app_id\"}, application_name)"
    }
   },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, exported_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Executors - tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active tasks",
   "type": "timeseries",
   "description": "Shows the number of active tasks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metrics_executor_activeTasks{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Max tasks",
   "type": "timeseries",
   "description": "Shows the number of Max tasks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metrics_executor_maxTasks{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Failed Tasks Total",
   "type": "timeseries",
   "description": "Shows the total number of failed tasks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metrics_executor_failedTasks_total{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Completed Tasks Total per minute",
   "type": "timeseries",
   "description": "Shows the total number of completed tasks per minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_completedTasks_total{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executors - memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "description": "Shows the memory used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_memoryUsed_bytes{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "timeseries",
   "description": "Total amount of memory available for storage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_maxMemory_bytes{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Process Tree JVM RSS Memory",
   "type": "timeseries",
   "description": "Resident Set Size: number of pages the process has in real memory. This is just the pages which count toward text, data, or stack space. This does not include pages which have not been demand-loaded in, or which are swapped out. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_ProcessTreeJVMRSSMemory_bytes{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Process Tree JVM VMemory",
   "type": "timeseries",
   "description": "Virtual memory size in bytes. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_ProcessTreeJVMVMemory_bytes{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executors - Garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minor GC Count total",
   "type": "timeseries",
   "description": "Total minor GC count per minute. For example, the garbage collector is one of Copy, PS Scavenge, ParNew, G1 Young Generation and so on.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_MinorGCCount_total{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Major GC Count total",
   "type": "timeseries",
   "description": "Total major GC count per minute. For example, the garbage collector is one of MarkSweepCompact, PS MarkSweep, ConcurrentMarkSweep, G1 Old Generation and so on.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_MajorGCCount_total{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Minor GC Time",
   "type": "timeseries",
   "description": "Elapsed total minor GC time per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_MinorGCTime_seconds_total{cluster=\"$cluster\",application_id=\"$spark_app_id\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Major GC Time",
   "type": "timeseries",
   "description": "Elapsed total major GC time per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_MajorGCTime_seconds_total{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executors - Cores/Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "total Cores",
   "type": "timeseries",
   "description": "Shows total cores used per executor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_executor_totalCores{cluster=\"$cluster\", application_id=\"$spark_app_id\", namespace=\"$namespace\"}",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "disk used",
   "type": "timeseries",
   "description": "Shows disk used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_executor_diskUsed_bytes{cluster=\"$cluster\",application_id=\"$spark_app_id\", namespace=\"$namespace\"}",
     "legendFormat": "application_name={{application_name}},executor_id={{executor_id}}"
    }
   ]
  },
  {
   "title": "Driver Block Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "maxOnHeapMem",
   "type": "timeseries",
   "description": "Shows driver block manager max on heap memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_BlockManager_memory_maxOnHeapMem_MB_Number\"}",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "remainingOnHeapMem",
   "type": "timeseries",
   "description": "Shows driver block manager current remaining on heap memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\",  __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_BlockManager_memory_remainingOnHeapMem_MB_Number\"}",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "DAG Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DAGScheduler jobs per minute",
   "type": "timeseries",
   "description": "Shows the number of all DAGScheduler jobs per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_DAGScheduler_job_allJobs_Number\"}[1m])",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "DAGScheduler active jobs number",
   "type": "timeseries",
   "description": "Shows the number of all DAGScheduler current active jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_DAGScheduler_job_activeJobs_Number\"}",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "DAGScheduler processed messages per minute",
   "type": "timeseries",
   "description": "Shows DAGScheduler processed messages per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_DAGScheduler_messageProcessingTime_Count\"}[1m])",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "Mean message processing time",
   "type": "timeseries",
   "description": "Shows DAGScheduler mean message processing time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_DAGScheduler_messageProcessingTime_Mean\"}",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "description": "JVM CPU time per minute",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate({cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_JVMCPU_jvmCpuTime_Number\"}[1m])",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Completed Batch jobs per minute",
   "type": "timeseries",
   "description": "Shows total streaming Completed Batch jobs per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_${application_name}_StreamingMetrics_streaming_totalCompletedBatches_Number\"}[1m])",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "Retained Completed Batch jobs",
   "type": "timeseries",
   "description": "Shows retained streaming Completed Batch jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_${application_name}_StreamingMetrics_streaming_retainedCompletedBatches_Number\"}",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "Time from processing start time of the last completed batch",
   "type": "stat",
   "description": "Shows the time from processing start time of the last completed batch",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() * 1000 - {cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_${application_name}_StreamingMetrics_streaming_lastCompletedBatch_processingStartTime_Number\"}"
    }
   ]
  },
  {
   "title": "Time from processing end time of the last completed batch",
   "type": "stat",
   "description": "Shows the time from processing end time of the last completed batch",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() * 1000 - {cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_${application_name}_StreamingMetrics_streaming_lastCompletedBatch_processingEndTime_Number\"}"
    }
   ]
  },
  {
   "title": "Time from submission of the last completed batch",
   "type": "stat",
   "description": "Shows the time from submission of the last completed batch",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() * 1000 - {cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_${application_name}_StreamingMetrics_streaming_lastCompletedBatch_submissionTime_Number\"}"
    }
   ]
  },
  {
   "title": "LiveListenerBus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Events posted per minute",
   "type": "timeseries",
   "description": "Shows the number of events posted per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_LiveListenerBus_numEventsPosted_Count\"}[1m])",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  },
  {
   "title": "streaming scheduler StreamingListenerBus Count per minute",
   "type": "timeseries",
   "description": "streaming scheduler StreamingListenerBus Count per minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({cluster=\"$cluster\", namespace=\"$namespace\", __name__=~\"metrics_${spark_app_id_prefix}_${spark_app_id_postfix}_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_streaming_scheduler_StreamingListenerBus_Count\"}[1m])",
     "legendFormat": "General Metric: ${spark_app_id_prefix}_${spark_app_id_postfix}"
    }
   ]
  }
 ]
}