{
 "title": "Spark Operator",
 "description": "Spark Operator and Spark Applications metrics",
 "tags": [ "Spark" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, exported_namespace)"
   },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", exported_namespace=\"$namespace\"}, exported_pod)"
   },
   {
    "name": "interval",
    "query": "1m,2m,5m,10m,30m,1h,2h,5h,10h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Operator Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operator Status",
   "type": "stat",
   "description": "Health status of Spark Operator",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{cluster=\"$cluster\", exported_namespace=~\"$namespace\", deployment=~\"sparkoperator.*.controller\"})*sum(kube_deployment_status_replicas_available{cluster=\"$cluster\", exported_namespace=~\"$namespace\", deployment=~\"sparkoperator.*.webhook\"})*( sum(kube_deployment_status_replicas_available{cluster=\"$cluster\", exported_namespace=~\"$namespace\", deployment=~\"spark-history-server.*\"} OR on() vector(1)) - 0.5) "
    }
   ]
  },
  {
   "title": "Active Controller Replicas",
   "type": "stat",
   "description": "Number of Spark Operator's controller running pods.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"sparkoperator.*\", exported_pod!~\".*webhook.*\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Count",
   "type": "stat",
   "description": "Shows the number of pods related to the Operator in the namespace",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"sparkoperator.*\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "description": "Shows pod state",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{cluster=\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"sparkoperator.*\"}) by(exported_namespace, exported_pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Container Restart",
   "type": "timeseries",
   "description": "Shows the number of each container restarts in the pod",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "kube_pod_container_status_restarts_total{cluster=\"$cluster\",exported_namespace=~\"$namespace\", exported_pod=~\"sparkoperator.*\"}",
     "legendFormat": "{{ container }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "History Server Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spark History Server Status",
   "type": "stat",
   "description": "Health status of Spark History Server",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\", exported_namespace=\"$namespace\", deployment=\"spark-history-server\"}"
    }
   ]
  },
  {
   "title": "Active Replicas",
   "type": "stat",
   "description": "Number of Spark History Server's running pods.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=~\"spark-history-server.*\", exported_pod!~\".*webhook.*\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Count",
   "type": "stat",
   "description": "Shows the number of pods related to Spark History Server in the namespace",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"spark-history-server.*\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "description": "Shows pod state",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{cluster=\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"spark-history-server.*\"}) by(exported_namespace, exported_pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Container Restart",
   "type": "timeseries",
   "description": "Shows the number of each container restarts in the pod",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "kube_pod_container_status_restarts_total{cluster=\"$cluster\",exported_namespace=~\"$namespace\", exported_pod=~\"spark-history-server.*\"}",
     "legendFormat": "{{ container }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Spark Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total apps count",
   "type": "stat",
   "description": "Total number of SparkApplication handled by the Operator.\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_count{cluster=\"$cluster\", namespace=\"$namespace\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Number of submitted apps",
   "type": "stat",
   "description": "Total number of SparkApplication spark-submitted by the Operator.\n",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_submit_count{cluster=\"$cluster\", namespace=\"$namespace\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Running apps count",
   "type": "stat",
   "description": "Total number of SparkApplication which are currently running.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_running_count{cluster=\"$cluster\", namespace=\"$namespace\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Running executors count",
   "type": "stat",
   "description": "Total number of Spark Executors which are currently running.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_running_count{cluster=\"$cluster\", namespace=\"$namespace\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Number of failed apps",
   "type": "stat",
   "description": "Total number of SparkApplication which failed to complete.\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_failure_count{cluster=\"$cluster\", namespace=\"$namespace\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Number of successfully completed apps",
   "type": "stat",
   "description": "Total number of SparkApplication which completed successfully.\n",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_success_count{cluster=\"$cluster\", namespace=\"$namespace\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Executors completed successfully",
   "type": "stat",
   "description": "Total number of Spark Executors which completed successfully.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_success_count{cluster=\"$cluster\", namespace=\"$namespace\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Failed executors count",
   "type": "stat",
   "description": "Total number of Spark Executors which failed.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_failure_count{cluster=\"$cluster\", namespace=\"$namespace\"} or vector(0))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows CPU usage by pods in the namespace",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container!=\"POD\", namespace=\"$namespace\",name!=\"\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\",exported_namespace=~\"$namespace\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "CPU Quota Limits"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\",exported_namespace=~\"$namespace\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "CPU Quota Requests"
    }
   ]
  },
  {
   "title": "CPU Usage By Pods",
   "type": "table",
   "description": "Shows detailed information about CPU usage by pods in the namespace. \n\nClick on the pod name to go to the dashboard with the pod detailed information",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",image!=\"\", container!=\"POD\", name!=\"\", namespace=\"$namespace\"}[1m])) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\",exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\",exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", name!=\"\", namespace=\"$namespace\"}[1m])) by (pod) / sum(label_replace(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.*)\")) by (pod)"
    }
   ]
  },
  {
   "title": "Work Queue Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of adds",
   "type": "timeseries",
   "description": "Total number of adds handled by workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(spark_application_controller_adds{cluster=\"$cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of retries",
   "type": "timeseries",
   "description": "Total number of retries handled by workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(spark_application_controller_retries{cluster=\"$cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Longest running processor",
   "type": "timeseries",
   "description": "Longest running processor in microseconds\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(spark_application_controller_longest_running_processor_microseconds{cluster=\"$cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Unfinished work",
   "type": "timeseries",
   "description": "Unfinished work in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(spark_application_controller_unfinished_work_seconds{cluster=\"$cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows memory usage by pods in the namespace",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\", container!=\"POD\", name!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\",exported_namespace=~\"$namespace\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "Memory Quota Limits"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\",exported_namespace=~\"$namespace\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "Memory Quota Requests"
    }
   ]
  },
  {
   "title": "Memory Usage By Pods",
   "type": "table",
   "description": "Shows detailed information about memory usage by pods in the namespace. \n\nClick on the pod name to go to the dashboard with the pod detailed information",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"POD\", name!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\", exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(rate(container_memory_working_set_bytes{image!=\"\", container!=\"POD\", name!=\"\", namespace=\"$namespace\"}[1m])) by (pod) / sum(label_replace(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", exported_namespace=~\"$namespace\"}, \"pod\", \"$1\", \"exported_pod\", \"(.*)\")) by (pod)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk I/O utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\", container!~\"POD|\"}[5m])) by (namespace)",
     "legendFormat": "{{ namespace }} - reads bytes"
    },
    {
     "expr": "sum (rate(container_fs_writes_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\", container!=\"\"}[5m])) by (namespace)",
     "legendFormat": "{{ namespace }} -  written bytes"
    }
   ]
  },
  {
   "title": "Conteiner IOps",
   "type": "timeseries",
   "description": "Count of writes/reads completed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!~\"POD|\"}[5m])) by (namespace)",
     "legendFormat": "{{ namespace }} reading"
    },
    {
     "expr": "sum (rate(container_fs_writes_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!~\"POD|\"}[5m])) by (namespace)",
     "legendFormat": "{{ namespace }} writing"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive/Transmit Bandwidth",
   "type": "timeseries",
   "description": "Shows network traffic in bytes per second for the pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "receive: {{pod}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "transmit: {{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Received/Transmitted Packets",
   "type": "timeseries",
   "description": "Shows network packets for pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "received: {{pod}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)    ",
     "legendFormat": "transmitted: {{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Received/Transmitted Packets Dropped",
   "type": "timeseries",
   "description": "Shows dropped packets for pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "receive: {{pod}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "transmit: {{pod}}"
    }
   ]
  }
 ]
}